portageAGS2ArcaneV3
arcaneframework/framework pull request #610
Opened 2023-04-01 12:11 UTC by gratienj

2023-04-01 12:29 UTC, grospelliergilles requested changes
Il faudrait faire un rebase sur main car sinon tu intègres toutes les modifications depuis le moment où tu as tiré ta branche.

Il faudrait aussi séparer si possible le commit concernant 'axlstar' de celui concernant 'arcane' car il faut ensuite modifier le numéro de version de 'axlstar' et indiquer dans 'arcane' qu'on a besoin de cette version.

Si tu veux je peux faire cela mais dans ce cas il ne faut plus toucher à cette branche tant que je n'ai pas fait ces modifications.

2023-04-03 07:47 UTC, gratienj commented
Ok je refais la manip : j ai un push request que pour la partie axlstar en incrementant la version à la 2.1.2

et je vais refaire un pull request pour la partie arcane après un rebase.

@grospelliergilles 
Est ce que je peux lancer le merge pour la partie axlstar si tous les tests passe

2023-04-03 08:13 UTC, grospelliergilles commented
> @grospelliergilles Est ce que je peux lancer le merge pour la partie axlstar si tous les tests passe

Oui.

2023-04-05 08:37 UTC, grospelliergilles commented
Salut @gratienj . J'ai vu que tu avais fait une autre PR du coup je ferme celle là car cela pose problème avec Codacy. Au besoin on pourra la ré-ouvrir.

2023-04-05 08:37 UTC, closed without merging