GraphOnDof evolution to manage DualNode to Link connectivity
arcaneframework/framework pull request #612
Opened 2023-04-03 10:48 UTC by gratienj

2023-04-03 10:55 UTC, gratienj commented
GraphOnDof evolution : add DualNode to Link connectivity

2023-04-03 13:30 UTC, grospelliergilles requested changes
Il faudrait remplacer les `for(auto ... : )` par `for( const auto& ... : )` car sinon coverity génère un 'défaut'.

2023-04-03 13:30 UTC, grospelliergilles commented on arcane/src/arcane/core/ItemEnumerator.h
>  //! Enumérateur generique d'un groupe de degrés de liberté
Tu n'auras plus besoin de ces énumérateurs ?

2023-04-03 13:38 UTC, gratienj commented on arcane/src/arcane/core/ItemEnumerator.h
>  //! Enumérateur generique d'un groupe de degrés de liberté
Je les ai redéfinies dans ArcGeoSim pour les codes clients qui continue à les utiliser

2023-04-03 14:05 UTC, grospelliergilles commented on arcane/src/arcane/core/ItemEnumerator.h
>  //! Enumérateur generique d'un groupe de degrés de liberté
Ok parfait c'est une bonne idée.

2023-04-04 08:31 UTC, grospelliergilles commented
Du coup il ne reste plus qu'à  remplacer les `for(auto ... : )` par `for( const auto& ... : )` et je pense que c'est bon pour la PR.

2023-04-05 07:56 UTC, merged